### ISSUE TITLE
annotation of each thematic role (e.g. ARG0)

### ISSUE THREAD

**Issue by midannii** [machinereading/BERT_for_Korean_SRL#1]
Hi, I'm trying to SRL with your models
and here's a question.

What is the meanings of each thematic role?
I tried to find annotation but I can't. 

Thank you :)

**Comment by hahmyg** [comment]
Thank you for your interests.

Plaese check this slide:  https://web.stanford.edu/~jurafsky/slp3/slides/22_SRL.pdf

It would be helpful to understand the basic concept of SRL

**Comment by midannii** [comment]
Thanks for your help but I still cannot find about below 😭

`'ARGA','ARGM_CND', 'ARGM_DIS', 'ARGM_EXT', 'ARGM_INS', 'ARGM_EXT'`

**Comment by hahmyg** [comment]
Oh, those are may Korean specific labels :)
(They are proposed to Korean Standard SRL labels recently)

ARGA: ARGment. No different with ARG-N such as Arg5
ARGM_CND: CoNDitional modifier (e.g., between, than, ...)
ARGM_DIS: adverb for DIScourse (e.g., but, and, so that, ...)
ARGM_EXT: EXTent. (e.g., best, very, ...)
ARGM_INS: INStrument (for more specific tools than ARGM_MNR)

**Comment by midannii** [comment]
Thank you so much !!! :) 
And Here's my last questions 😅  
Which ARGN is the most similar to `ARGA` ?
and What's the meaning of `AUX`?
